#!/bin/bash
function getContainers() {
        echo $(podman ps | grep -v 'CONTAINER ID' | awk '{print $1}');
}
containers=$(podman ps | grep -v 'CONTAINER ID' | awk '{print $1}')
length=${#containers}
echo $length

while [ "$length" -gt "0" ]
do
        for i in $containers
        do
                podman stop $i > /dev/null
        done
        containers=$(podman ps | grep -v 'CONTAINER ID' | awk '{print $1}')
        length=${#containers}
done
