#!/bin/bash

isRunning=$(tmux ls | grep -o workspace)
clear
if [[ "$isRunning" == "workspace" ]]; then
	tmux attach -t workspace:workspace
else
	tmux new-session -s workspace -n workspace 'distrobox enter workspace -nw'
fi
